### ISSUE TITLE
Cardupload - create card directory if it does not exist yet

### ISSUE THREAD

**Issue by Shirisu** [nekocari/miniTCG#1]
It would be great if the card directory was already created by default - either directly in the setup itself or when uploading cards for the first time.

If the directory does not exist the following message is displayed

> Warning: mkdir(): No such file or directory in miniTCG\helper\cardupload.php on line 43
> Ordner existiert bereits.

The message "Ordner existiert bereits." is missleading in this case.

**Comment by nekocari** [comment]
The cardupload class is now updated and a new method was added, to create the path for the deck images folder, if it doesn't exist.
If the folder exists but is not writable, the rights will be changed so the upload shouldn't fail anymore.
