### ISSUE TITLE
localhost URLs

### ISSUE THREAD

**Issue by mad-d-y** [nekocari/miniTCG#15]
Hello!

I'm very new to php so might have just missed something obvious, but every link seems to be taking me to http://localhost/eclipse/miniTCG/xxxx. Everything works fine if I replace the localhost/eclipse/miniTCG with my own URL, but is there something in the setup I need to change?

**Comment by nekocari** [comment]
Seems like you need to to change this in the constants file:

 define('BASE_URI', 'http://localhost/eclipse/miniTCG/');

**Comment by mad-d-y** [comment]
Oh my gosh, I'm so sorry - I've no idea how I missed that. All fixed! thank you so much!

**Comment by nekocari** [comment]
It's fine. 
Hope it works now. :)
