### ISSUE TITLE
Category overview page - empty page when no card decks are active

### ISSUE THREAD

**Issue by Shirisu** [nekocari/miniTCG#2]
When you open a category overview page, the page is empty except for the headline.
Maybe a message should be displayed that there are no carddecks in this category yet or the category should be hidden.

Or the page should look like the "all" page for categories.

![image](https://user-images.githubusercontent.com/16443057/114507824-f570af00-9c33-11eb-9f30-3a5ad9e59fd1.png)

**Comment by nekocari** [comment]
Empty categories should no longer show up in the navigation.
