### ISSUE TITLE
i think router not work

### ISSUE THREAD

**Issue by c4ei** [nekocari/miniTCG#22]
https://admin.c4ex.net/

i click login but 404
![image](https://github.com/nekocari/miniTCG/assets/98538921/05a9d6f7-f54f-4b12-8032-fe1bff211fae)

**Comment by nekocari** [comment]
I'm not sure what the issue is tbh. My knowledge about rewrite rules is limited. Are you sure you can use htaccess files for rewrite rules?

**Comment by gavintfn** [comment]
https://admin.c4ex.net/setup/setup.php  comes back with:
SQLSTATE[HY000] [1049] Unknown database 'miniTCG'.
You have not created a DB, nor run setup yet, as such the routing table from the database is unable to be accessed.  Create a blank database schema and update your credentials for that database in config/constants.php as stated in the directions.
At that point the .htaccess file, which routes all requests to index.php, will be able to redirect appropriately to signin.php
