### ISSUE TITLE
Bug: Double Card is shown two times in Trade In Game

### ISSUE THREAD

**Issue by Kasuna89** [nekocari/miniTCG#27]
![image](https://github.com/user-attachments/assets/6131604d-513d-40e8-b0d6-69cfe70710b6)

I just have three cards of the same type in the cardmanager, not four.
Two in Keep and one in Trade.

**Comment by nekocari** [comment]
https://github.com/nekocari/miniTCG/commit/5c92a8b9ed189d762ff15c6b2960c6869c218f8b should fix this issue
