### ISSUE TITLE
Number on Card Manager Link

### ISSUE THREAD

**Issue by Kasuna89** [nekocari/miniTCG#29]
It would be cool if a number on the Card Manager would be shown when a new card is added to the profile. No matter if the new card is from a game, trade or anything else.

**Comment by nekocari** [comment]
<?php echo Card::getCount(['owner'=>$this->login->getUserId(),'status_id'=>CardStatus::getNew()->getId()]); ?> 
Will return the number of cards in "New". Add it anywhere you like.
