### ISSUE TITLE
Bug: Subsequently change of Cards in a Deck

### ISSUE THREAD

**Issue by Kasuna89** [nekocari/miniTCG#31]
If you subsequently change the number of cards in an existing deck, you can only change the number of cards that was set at the beginning (i.e. 9 cards at the beginning, will be changed to 16 cards, only 9 cards can still be changed). Only after changing the deck type the change will be applied.

**Comment by nekocari** [comment]
Added a check for related decks. They will now be updated as well. https://github.com/nekocari/miniTCG/commit/bd1ebcc513e8640fa507592a2270e12458c6380a
